# NumPy  - Operaciones

Tipos de operaciones:
 * Arreglos con Arreglos
 * Arreglos con escalares
 * Funciones universales
 * Iterando sobre arreglos

## Aritméticas

Es posible hacer operaciones aritméticas entre arreglos; y también, entre arreglos y escalares. Se usan los operadores aritméticos tradicionales.

In [1]:
import numpy as np
arr = np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# En Python, la siguiente división retorna un error
1/0

ZeroDivisionError: division by zero

In [6]:
# Sin embargo, en NumPy si dividimos arr/arr, obtendremos un Warning de división por cero, pero no se considera como un error! 
# Se reemplaza por 'NaN' (Not a Number)

arr/arr

C:\Users\Andrea\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# 1/arr también produce un warning, pero no un error. En la división 1/0 se obtiene 'inf' (infinito)
1/arr

C:\Users\Andrea\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Diferencia con las listas de Python 

In [9]:
# Listas
lista = [1, 2,5] 
lista2 = [3, 4]

In [10]:
lista + lista2

[1, 2, 5, 3, 4]

In [12]:
lista * 4 #Repite la lista 4 veces

[1, 2, 5, 1, 2, 5, 1, 2, 5, 1, 2, 5]

In [13]:
# Arreglos NumPy
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### Multiplicación matriz por una matriz 

In [17]:
mat = np.array([[1,2],[3,4]])

In [18]:
mat

array([[1, 2],
       [3, 4]])

In [19]:
# El operador * multiplica los elementos uno a uno (NO es multiplicación matricial)
mat * mat

array([[ 1,  4],
       [ 9, 16]])

In [20]:
# Para la multiplicación matricial se usa dot()
mat.dot(mat)

array([[ 7, 10],
       [15, 22]])

In [21]:
mat2 = np.array([[10],[20]])

In [22]:
mat2

array([[10],
       [20]])

In [23]:
mat.dot(mat2)

array([[ 50],
       [110]])

## Funciones Universales con Arreglos

Numpy viene con muchas [funciones universales para arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), las cuales son operaciones matemáticas que se pueden usar para efectuar una operación sobre el arreglo. Por ejemplo:

In [24]:
# Raíz cuadrada
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
# exponencial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [26]:
np.max(arr) # igual que arr.max()

9

In [27]:
# Funciones trigonométricas
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [28]:
# Logaritmo
np.log(arr)

C:\Users\Andrea\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Iterando sobre arreglos

In [29]:
# Arreglo 1-D
arr = np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Iterando sobre un arreglo unidimensional
for item in arr:
    print(item)

0
1
2
3
4
5
6
7
8
9


In [31]:
# Arreglo 2-D
arr = np.arange(0,100).reshape(10,10)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
# Iterando por filas sobre un arreglo 2-D
for fila in arr:
    print(fila)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]


In [33]:
# Si se quiere hacer una operación sobre cada uno de los valores, es necesario usar la propiedad "flat"
for fila in arr.flat:
    print(fila)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


### Consultar más info: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html