# NumPy Indices y Selección

En este notebook veremos como seleccionar elementos o grupos de elementos de un arreglo de Numpy.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Índices y selección de elementos mediante corchetes [ ]
La forma más sencilla de seleccionar un elemento o un conjunto de ellos de un arreglo es muy similar a las listas de Python:

In [4]:
# Obtiene el elemento ubicado en el índice dado
arr[8]

8

In [5]:
# Obtiene los elementos en el rango dado (sin incluir el límite superior)
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:8:2]

array([0, 2, 4, 6])

In [10]:
arr[-1]

10

In [11]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Broadcasting

Los arreglos de Numpy se diferencian de las listas de Python porque tienen la habilidad de hacer "broadcast":

In [12]:
# Asignar un valor dado a un rango de índices en un arreglo (Broadcasting)
arr[0:5]=100

# Resultado
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr[0::2]=-1

arr

array([ -1, 100,  -1, 100,  -1,   5,  -1,   7,  -1,   9,  -1])

In [14]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

# Resultado
trozo_de_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
# Cambios 
trozo_de_arr[:]=99

#Show Slice again
trozo_de_arr

array([99, 99, 99, 99, 99, 99])

** OJO: los cambios también ocurren en el arreglo original!**

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

** Los datos no se copian, un "trozo" de un arreglo es simplemente una vista del arreglo original! ** Esto sirve para prevenir problemas de memoria!

In [21]:
# Para obtener una copia, es necesario usar el método copy()
copia_arr = arr.copy()

copia_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
copia_arr[:] = 100

copia_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indices de arreglos 2D (matrices)

El formato general es **arr_2d[fila][col]** o **arr_2d[fila,col]**. Por claridad, se recomienda la notación con coma.

In [24]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
# Indexando una fila
arr_2d[1]


array([20, 25, 30])

In [26]:
# El formato es arr_2d[fila][col] o arr_2d[fila,col]

# Accediendo a un elemento particular (formato 1)
arr_2d[1][0]

20

In [27]:
# Accediendo a un elemento particular (formato 2)
arr_2d[1,0]

20

In [28]:
# trozos 2D de arreglos

# Traer las dos primeras filas de la matriz
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [29]:
# Traer la última columna
arr_2d[2,:]

array([35, 40, 45])

In [30]:
# Traer las últimas 2 columnas
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [0]:
# Traer la matriz 2x2 de la esquina superior derecha
arr_2d[:2,1:]

## "Indexado elegante" (fancy indexing)

Se permite indexar filas o columnas enteras de una sola vez:

In [31]:
# matriz
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
# Tamaño de la fila 1
arr_length = arr2d.shape[1]

arr_length

10

In [34]:
# Inicialización

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

El "indexado elegante" permite lo siguiente:

In [35]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [36]:
# Y también en cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selección condicional


In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr>4

In [40]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
x = 6
arr[arr>x]

array([ 7,  8,  9, 10])